### ISSUE TITLE
Update website page showing tools to create DZI images

### ISSUE THREAD

**Issue by tenbob** [openseadragon/openseadragon.github.com#23]
Hi. Could someone please update the webpage that lists various tools to create DZI images. The page is [here](https://github.com/openseadragon/openseadragon.github.com/tree/master/examples/creating-zooming-images).

Many of the tools listed are deprecated or disappeared long ago. I can't find Microsoft Deep Zoom Composer or Interactive Composite Editor at all. What do people use currently?

**Comment by tenbob** [comment]
Typo

**Comment by iangilman** [comment]
Excellent point! I have now done so. Here's the PR: 

https://github.com/openseadragon/site-build/pull/274 (Note that it's actually in a different repository than the one you pointed to... We have one for the site source and another for the built site; I know it's confusing!)

... And the page is updated: 

https://openseadragon.github.io/examples/creating-zooming-images/

My recommendation is to use VIPS!

**Comment by tenbob** [comment]
Thanks for the update and the recommendation to use VIPS.
